apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-exinity-task
  namespace: exinity-task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-exinity-task
  template:
    metadata:
      labels:
        app: go-exinity-task
    spec:
      containers:
        - name: go-exinity-task
          image: go-exinity-task:latest  # Your Go API Docker image
          ports:
            - containerPort: 50051
          envFrom:
            - secretRef:
                name: api-db-secret
            - configMapRef:
                name: go-api-config   # Reference the ConfigMap here
