provider:
  binance:
    scheme: "wss"
    host: "stream.binance.com:443"
    path: "/stream"
    key: "streams"
    separator: "@trade"
    symbols:
      - btcusdt
      - ethusdt
      - pepeusdt
service:
  network: tcp
  host: ""
  port: 50051
database:
  password: "mypassword123!"
  username: "postgress"
  host: "go-exinity-task-postgress"
  port: 5432
  database: exinity_task
