apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: exinity-task
type: Opaque
data:
  POSTGRES_DB: ZXhpbml0eV90YXNr             # exinity_task
  POSTGRES_USER: cG9zdGdyZXNz           # postgress
  POSTGRES_PASSWORD: bXlwYXNzd29yZDEyMyE=  # mypassword123!
