// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.2
// source: internal/app/api/proto/candle.proto

package candle

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Candle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OpenTime      int64                  `protobuf:"varint,2,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`
	Open          float64                `protobuf:"fixed64,3,opt,name=open,proto3" json:"open,omitempty"`
	High          float64                `protobuf:"fixed64,4,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,5,opt,name=low,proto3" json:"low,omitempty"`
	Close         float64                `protobuf:"fixed64,6,opt,name=close,proto3" json:"close,omitempty"`
	Volume        float64                `protobuf:"fixed64,7,opt,name=volume,proto3" json:"volume,omitempty"`
	CloseTime     int64                  `protobuf:"varint,8,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candle) Reset() {
	*x = Candle{}
	mi := &file_internal_app_api_proto_candle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candle) ProtoMessage() {}

func (x *Candle) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_api_proto_candle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candle.ProtoReflect.Descriptor instead.
func (*Candle) Descriptor() ([]byte, []int) {
	return file_internal_app_api_proto_candle_proto_rawDescGZIP(), []int{0}
}

func (x *Candle) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Candle) GetOpenTime() int64 {
	if x != nil {
		return x.OpenTime
	}
	return 0
}

func (x *Candle) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Candle) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Candle) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Candle) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *Candle) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Candle) GetCloseTime() int64 {
	if x != nil {
		return x.CloseTime
	}
	return 0
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"` // Optionally subscribe to specific symbols
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_internal_app_api_proto_candle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_api_proto_candle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_api_proto_candle_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

var File_internal_app_api_proto_candle_proto protoreflect.FileDescriptor

const file_internal_app_api_proto_candle_proto_rawDesc = "" +
	"\n" +
	"#internal/app/api/proto/candle.proto\x12\x06candle\"\xc4\x01\n" +
	"\x06Candle\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1b\n" +
	"\topen_time\x18\x02 \x01(\x03R\bopenTime\x12\x12\n" +
	"\x04open\x18\x03 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x04 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x05 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\x06 \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\a \x01(\x01R\x06volume\x12\x1d\n" +
	"\n" +
	"close_time\x18\b \x01(\x03R\tcloseTime\",\n" +
	"\x10SubscribeRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols2O\n" +
	"\rCandleService\x12>\n" +
	"\x10SubscribeCandles\x12\x18.candle.SubscribeRequest\x1a\x0e.candle.Candle0\x01BDZBgithub.com/AkyurekDogan/exinity-task/internal/app/api/proto;candleb\x06proto3"

var (
	file_internal_app_api_proto_candle_proto_rawDescOnce sync.Once
	file_internal_app_api_proto_candle_proto_rawDescData []byte
)

func file_internal_app_api_proto_candle_proto_rawDescGZIP() []byte {
	file_internal_app_api_proto_candle_proto_rawDescOnce.Do(func() {
		file_internal_app_api_proto_candle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_app_api_proto_candle_proto_rawDesc), len(file_internal_app_api_proto_candle_proto_rawDesc)))
	})
	return file_internal_app_api_proto_candle_proto_rawDescData
}

var file_internal_app_api_proto_candle_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_app_api_proto_candle_proto_goTypes = []any{
	(*Candle)(nil),           // 0: candle.Candle
	(*SubscribeRequest)(nil), // 1: candle.SubscribeRequest
}
var file_internal_app_api_proto_candle_proto_depIdxs = []int32{
	1, // 0: candle.CandleService.SubscribeCandles:input_type -> candle.SubscribeRequest
	0, // 1: candle.CandleService.SubscribeCandles:output_type -> candle.Candle
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_app_api_proto_candle_proto_init() }
func file_internal_app_api_proto_candle_proto_init() {
	if File_internal_app_api_proto_candle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_app_api_proto_candle_proto_rawDesc), len(file_internal_app_api_proto_candle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_app_api_proto_candle_proto_goTypes,
		DependencyIndexes: file_internal_app_api_proto_candle_proto_depIdxs,
		MessageInfos:      file_internal_app_api_proto_candle_proto_msgTypes,
	}.Build()
	File_internal_app_api_proto_candle_proto = out.File
	file_internal_app_api_proto_candle_proto_goTypes = nil
	file_internal_app_api_proto_candle_proto_depIdxs = nil
}
