// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/app/infrastructure/repository/rating.go

// Package repository is a generated GoMock package.
package repository

import (
	reflect "reflect"

	model "github.com/AkyurekDogan/exinity-task/internal/app/infrastructure/model"
	gomock "github.com/golang/mock/gomock"
)

// MockPartnerRating is a mock of PartnerRating interface.
type MockPartnerRating struct {
	ctrl     *gomock.Controller
	recorder *MockPartnerRatingMockRecorder
}

// MockPartnerRatingMockRecorder is the mock recorder for MockPartnerRating.
type MockPartnerRatingMockRecorder struct {
	mock *MockPartnerRating
}

// NewMockPartnerRating creates a new mock instance.
func NewMockPartnerRating(ctrl *gomock.Controller) *MockPartnerRating {
	mock := &MockPartnerRating{ctrl: ctrl}
	mock.recorder = &MockPartnerRatingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPartnerRating) EXPECT() *MockPartnerRatingMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockPartnerRating) Get(f model.Filter) (*model.Rating, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", f)
	ret0, _ := ret[0].(*model.Rating)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPartnerRatingMockRecorder) Get(f interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPartnerRating)(nil).Get), f)
}
